/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SalesReturnsRouteImport } from './routes/sales-returns'
import { Route as QuotationsRouteImport } from './routes/quotations'
import { Route as ProformaInvoicesRouteImport } from './routes/proforma-invoices'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PartiesRouteImport } from './routes/parties'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as GstRouteImport } from './routes/gst'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as DeliveryChallansRouteImport } from './routes/delivery-challans'
import { Route as CreditNotesRouteImport } from './routes/credit-notes'
import { Route as CashAndBankRouteImport } from './routes/cash-and-bank'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesReturnsRoute = SalesReturnsRouteImport.update({
  id: '/sales-returns',
  path: '/sales-returns',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationsRoute = QuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProformaInvoicesRoute = ProformaInvoicesRouteImport.update({
  id: '/proforma-invoices',
  path: '/proforma-invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesRoute = PartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const GstRoute = GstRouteImport.update({
  id: '/gst',
  path: '/gst',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryChallansRoute = DeliveryChallansRouteImport.update({
  id: '/delivery-challans',
  path: '/delivery-challans',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditNotesRoute = CreditNotesRouteImport.update({
  id: '/credit-notes',
  path: '/credit-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const CashAndBankRoute = CashAndBankRouteImport.update({
  id: '/cash-and-bank',
  path: '/cash-and-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cash-and-bank': typeof CashAndBankRoute
  '/credit-notes': typeof CreditNotesRoute
  '/delivery-challans': typeof DeliveryChallansRoute
  '/expenses': typeof ExpensesRoute
  '/gst': typeof GstRoute
  '/invoices': typeof InvoicesRoute
  '/items': typeof ItemsRoute
  '/login': typeof LoginRoute
  '/parties': typeof PartiesRoute
  '/payments': typeof PaymentsRoute
  '/proforma-invoices': typeof ProformaInvoicesRoute
  '/quotations': typeof QuotationsRoute
  '/sales-returns': typeof SalesReturnsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cash-and-bank': typeof CashAndBankRoute
  '/credit-notes': typeof CreditNotesRoute
  '/delivery-challans': typeof DeliveryChallansRoute
  '/expenses': typeof ExpensesRoute
  '/gst': typeof GstRoute
  '/invoices': typeof InvoicesRoute
  '/items': typeof ItemsRoute
  '/login': typeof LoginRoute
  '/parties': typeof PartiesRoute
  '/payments': typeof PaymentsRoute
  '/proforma-invoices': typeof ProformaInvoicesRoute
  '/quotations': typeof QuotationsRoute
  '/sales-returns': typeof SalesReturnsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cash-and-bank': typeof CashAndBankRoute
  '/credit-notes': typeof CreditNotesRoute
  '/delivery-challans': typeof DeliveryChallansRoute
  '/expenses': typeof ExpensesRoute
  '/gst': typeof GstRoute
  '/invoices': typeof InvoicesRoute
  '/items': typeof ItemsRoute
  '/login': typeof LoginRoute
  '/parties': typeof PartiesRoute
  '/payments': typeof PaymentsRoute
  '/proforma-invoices': typeof ProformaInvoicesRoute
  '/quotations': typeof QuotationsRoute
  '/sales-returns': typeof SalesReturnsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cash-and-bank'
    | '/credit-notes'
    | '/delivery-challans'
    | '/expenses'
    | '/gst'
    | '/invoices'
    | '/items'
    | '/login'
    | '/parties'
    | '/payments'
    | '/proforma-invoices'
    | '/quotations'
    | '/sales-returns'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cash-and-bank'
    | '/credit-notes'
    | '/delivery-challans'
    | '/expenses'
    | '/gst'
    | '/invoices'
    | '/items'
    | '/login'
    | '/parties'
    | '/payments'
    | '/proforma-invoices'
    | '/quotations'
    | '/sales-returns'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/cash-and-bank'
    | '/credit-notes'
    | '/delivery-challans'
    | '/expenses'
    | '/gst'
    | '/invoices'
    | '/items'
    | '/login'
    | '/parties'
    | '/payments'
    | '/proforma-invoices'
    | '/quotations'
    | '/sales-returns'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CashAndBankRoute: typeof CashAndBankRoute
  CreditNotesRoute: typeof CreditNotesRoute
  DeliveryChallansRoute: typeof DeliveryChallansRoute
  ExpensesRoute: typeof ExpensesRoute
  GstRoute: typeof GstRoute
  InvoicesRoute: typeof InvoicesRoute
  ItemsRoute: typeof ItemsRoute
  LoginRoute: typeof LoginRoute
  PartiesRoute: typeof PartiesRoute
  PaymentsRoute: typeof PaymentsRoute
  ProformaInvoicesRoute: typeof ProformaInvoicesRoute
  QuotationsRoute: typeof QuotationsRoute
  SalesReturnsRoute: typeof SalesReturnsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-returns': {
      id: '/sales-returns'
      path: '/sales-returns'
      fullPath: '/sales-returns'
      preLoaderRoute: typeof SalesReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotations': {
      id: '/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof QuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proforma-invoices': {
      id: '/proforma-invoices'
      path: '/proforma-invoices'
      fullPath: '/proforma-invoices'
      preLoaderRoute: typeof ProformaInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties': {
      id: '/parties'
      path: '/parties'
      fullPath: '/parties'
      preLoaderRoute: typeof PartiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gst': {
      id: '/gst'
      path: '/gst'
      fullPath: '/gst'
      preLoaderRoute: typeof GstRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-challans': {
      id: '/delivery-challans'
      path: '/delivery-challans'
      fullPath: '/delivery-challans'
      preLoaderRoute: typeof DeliveryChallansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-notes': {
      id: '/credit-notes'
      path: '/credit-notes'
      fullPath: '/credit-notes'
      preLoaderRoute: typeof CreditNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-and-bank': {
      id: '/cash-and-bank'
      path: '/cash-and-bank'
      fullPath: '/cash-and-bank'
      preLoaderRoute: typeof CashAndBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CashAndBankRoute: CashAndBankRoute,
  CreditNotesRoute: CreditNotesRoute,
  DeliveryChallansRoute: DeliveryChallansRoute,
  ExpensesRoute: ExpensesRoute,
  GstRoute: GstRoute,
  InvoicesRoute: InvoicesRoute,
  ItemsRoute: ItemsRoute,
  LoginRoute: LoginRoute,
  PartiesRoute: PartiesRoute,
  PaymentsRoute: PaymentsRoute,
  ProformaInvoicesRoute: ProformaInvoicesRoute,
  QuotationsRoute: QuotationsRoute,
  SalesReturnsRoute: SalesReturnsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
