#!/usr/bin/env npx tsx
/**
 * Ownership-Scoping Scanner (IDOR regression fence, static analysis)
 *
 * WHY THIS EXISTS:
 *   Every business-scoped tRPC procedure runs under `authorizedProcedure`
 *   (viewer/member/adminProcedure), which injects `ctx.businessId`. The ONLY
 *   thing standing between two tenants that share one physical database is the
 *   per-handler ownership filter — `eq(table.businessId, ctx.businessId)` (or
 *   `ctx.tenantId` for team-management endpoints). If a procedure accepts a
 *   client-supplied record identifier (`id`, `partyId`, `invoiceId`, …) but its
 *   handler never references `ctx.businessId`/`ctx.tenantId`, that filter is
 *   almost certainly missing — a cross-tenant IDOR.
 *
 *   `idor-authorization.test.ts` is the runtime fence for the procedures that
 *   existed when it was written. This scanner is the *static* fence that keeps
 *   the next id-accepting procedure from silently shipping without a scope.
 *
 * WHAT IT DOES:
 *   For every procedure defined under `packages/api/src/routers/` (and the
 *   shared document-router factory), it decides two things from the source:
 *     1. id-accepting  — the `.input(...)` schema declares a record identifier
 *                        (an `id` / `*Id` / `*Ids` field, or a bare
 *                        `z.string().uuid()`).
 *     2. ownership-scoped — the handler body references `ctx.businessId` or
 *                        `ctx.tenantId`.
 *   A procedure that is id-accepting but NOT ownership-scoped is a violation,
 *   unless it is listed (with a justification) in
 *   `scripts/ownership-scoping-allowlist.json`. The allowlist captures the
 *   handful of legitimate exceptions (id is itself the scope, scoping is
 *   delegated to a helper, unauthenticated/control-plane endpoints, etc.), so
 *   any NEW unscoped id-accepting procedure fails CI.
 *
 * This is a heuristic, not a type-checker. When it produces a false positive,
 * add the procedure to the allowlist with a one-line reason. When it misses a
 * real gap, tighten the heuristic here.
 *
 * Modes:
 *   --scan    Scan and report violations not covered by the allowlist.
 *             Exits 1 if any violation is found. (default)
 *   --list    List every id-accepting procedure and whether it is scoped,
 *             ignoring the allowlist. Used to build/refresh the baseline.
 *
 * Usage:
 *   npx tsx scripts/check-ownership-scoping.ts --scan
 *   npx tsx scripts/check-ownership-scoping.ts --list
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.resolve(__dirname, "..");

const ROUTERS_DIR = path.join(ROOT, "packages/api/src/routers");
const ROUTER_FILE = path.join(ROOT, "packages/api/src/router.ts");
// The per-document-type routers (quotation, creditNote, …) are generated by
// this factory; their list/getById/update/delete handlers — and their scoping —
// live here rather than in routers/, so scan it too.
const EXTRA_FILES = [path.join(ROOT, "packages/api/src/lib/document-router-factory.ts")];
const ALLOWLIST_FILE = path.join(__dirname, "ownership-scoping-allowlist.json");

// Matches a procedure definition, either inline in a router object
//   key: viewerProcedure
// or as a standalone export
//   export const name = adminProcedure
const PROCEDURE_KINDS = "public|protected|tenant|business|viewer|member|admin|authorized";
const PROC_ANCHOR = new RegExp(
  String.raw`(?:^[ \t]+(\w+)\s*:\s*(?:${PROCEDURE_KINDS})Procedure` +
    String.raw`|^export const (\w+)\s*=\s*(?:${PROCEDURE_KINDS})Procedure)`,
  "gm",
);

// An input field that names a record identifier: `id`, `partyId`, `invoiceIds`…
const ID_FIELD = /\b(?:id|[A-Za-z]+Id)s?\s*:\s*z\./;
// A bare uuid input (e.g. `.input(z.string().uuid())`).
const UUID_INPUT = /z\.string\(\)\.uuid\(\)/;
// Ownership scope references.
const SCOPE_REF = /ctx\.(?:businessId|tenantId)\b/;

interface Procedure {
  namespace: string;
  name: string;
  file: string;
  line: number;
  idAccepting: boolean;
  scoped: boolean;
}

// ---------------------------------------------------------------------------
// namespace mapping: routerVariable -> namespace key (from router.ts)
// ---------------------------------------------------------------------------

function buildNamespaceMap(): Map<string, string> {
  const map = new Map<string, string>();
  const content = fs.readFileSync(ROUTER_FILE, "utf-8");
  for (const m of content.matchAll(/(\w+):\s*(\w+Router)/g)) {
    map.set(m[2], m[1]); // authRouter -> auth
  }
  return map;
}

function collectFiles(dir: string): string[] {
  const out: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...collectFiles(full));
    } else if (entry.name.endsWith(".ts")) {
      out.push(full);
    }
  }
  return out;
}

// Resolve a display namespace for a file. When the file exports exactly one
// `xRouter`, use its mapped key; otherwise fall back to the file basename.
function namespaceForFile(file: string, content: string, nsMap: Map<string, string>): string {
  const routerExports = [...content.matchAll(/export const (\w+Router)\b/g)].map((m) => m[1]);
  const mapped = routerExports.map((r) => nsMap.get(r)).filter((x): x is string => Boolean(x));
  if (mapped.length === 1) return mapped[0];
  return path.basename(file, ".ts");
}

// Extract the `.input(...)` region of a procedure block: from `.input(` up to
// the resolver call (`.query`/`.mutation`/`.subscription`). Returns "" when the
// procedure declares no input.
function inputRegion(block: string): string {
  const inputIdx = block.indexOf(".input(");
  if (inputIdx === -1) return "";
  const rest = block.slice(inputIdx);
  const resolverMatch = rest.match(/\.(query|mutation|subscription)\s*\(/);
  return resolverMatch ? rest.slice(0, resolverMatch.index) : rest;
}

function scanFile(file: string, nsMap: Map<string, string>): Procedure[] {
  const content = fs.readFileSync(file, "utf-8");
  const namespace = namespaceForFile(file, content, nsMap);

  // Collect procedure anchors with their positions.
  const anchors: Array<{ name: string; index: number }> = [];
  for (const m of content.matchAll(PROC_ANCHOR)) {
    anchors.push({ name: m[1] ?? m[2], index: m.index ?? 0 });
  }

  const procs: Procedure[] = [];
  for (let i = 0; i < anchors.length; i++) {
    const start = anchors[i].index;
    const end = i + 1 < anchors.length ? anchors[i + 1].index : content.length;
    const block = content.slice(start, end);
    const region = inputRegion(block);

    const idAccepting = region !== "" && (ID_FIELD.test(region) || UUID_INPUT.test(region));
    const scoped = SCOPE_REF.test(block);
    const line = content.slice(0, start).split("\n").length;

    procs.push({ namespace, name: anchors[i].name, file, line, idAccepting, scoped });
  }
  return procs;
}

function scanAll(): Procedure[] {
  const nsMap = buildNamespaceMap();
  const files = [...collectFiles(ROUTERS_DIR), ...EXTRA_FILES.filter(fs.existsSync)];
  const procs: Procedure[] = [];
  for (const file of files) procs.push(...scanFile(file, nsMap));
  return procs;
}

function key(p: Procedure): string {
  return `${p.namespace}.${p.name}`;
}

function loadAllowlist(): Record<string, string> {
  if (!fs.existsSync(ALLOWLIST_FILE)) return {};
  const parsed = JSON.parse(fs.readFileSync(ALLOWLIST_FILE, "utf-8"));
  return parsed.allow ?? {};
}

function rel(file: string): string {
  return path.relative(ROOT, file);
}

// ---------------------------------------------------------------------------
// Commands
// ---------------------------------------------------------------------------

function cmdScan() {
  console.log("=== Ownership-Scoping Scan ===\n");

  const procs = scanAll();
  const allow = loadAllowlist();
  const idAccepting = procs.filter((p) => p.idAccepting);
  const unscoped = idAccepting.filter((p) => !p.scoped);

  const violations = unscoped.filter((p) => !(key(p) in allow));
  const allowedSeen = new Set(unscoped.filter((p) => key(p) in allow).map(key));

  console.log(
    `Scanned ${procs.length} procedures: ` +
      `${idAccepting.length} accept an identifier, ` +
      `${idAccepting.length - unscoped.length} are ownership-scoped, ` +
      `${unscoped.length} are not (${Object.keys(allow).length} allowlisted).\n`,
  );

  // Stale allowlist entries: listed but no longer flagged. Warn (do not fail) so
  // that *fixing* a procedure never breaks the build, but the drift is visible.
  const stale = Object.keys(allow).filter((k) => !allowedSeen.has(k));
  if (stale.length > 0) {
    console.log(`NOTE: ${stale.length} stale allowlist entr(y/ies) — no longer flagged, safe to remove:`);
    for (const k of stale) console.log(`  - ${k}`);
    console.log();
  }

  if (violations.length === 0) {
    console.log("PASS: every id-accepting procedure is ownership-scoped (or allowlisted).");
    return;
  }

  console.log(`FAIL: ${violations.length} id-accepting procedure(s) skip ownership scoping:\n`);
  for (const p of violations.sort((a, b) => key(a).localeCompare(key(b)))) {
    console.log(`  [GAP] ${key(p)}`);
    console.log(`        ${rel(p.file)}:${p.line}`);
  }
  console.log(
    "\nEach flagged handler accepts a client-supplied id but never references\n" +
      "ctx.businessId / ctx.tenantId. For each one, either:\n" +
      "  a) scope the query — add `eq(table.businessId, ctx.businessId)` to its\n" +
      "     WHERE clause (and return NOT_FOUND / null on no match), or\n" +
      "  b) if it is a genuine exception (id IS the scope, scoping is delegated to\n" +
      "     a helper, control-plane/unauthenticated endpoint, …), add it to\n" +
      `     ${rel(ALLOWLIST_FILE)} with a one-line justification.`,
  );
  process.exitCode = 1;
}

function cmdList() {
  const procs = scanAll();
  const allow = loadAllowlist();
  const idAccepting = procs.filter((p) => p.idAccepting).sort((a, b) => key(a).localeCompare(key(b)));

  console.log("=== All id-accepting procedures ===\n");
  for (const p of idAccepting) {
    const status = p.scoped ? "scoped " : key(p) in allow ? "ALLOW  " : "UNSCOPED";
    console.log(`  ${status}  ${key(p)}  (${rel(p.file)}:${p.line})`);
  }
}

const command = process.argv[2] ?? "--scan";
switch (command) {
  case "--scan":
    cmdScan();
    break;
  case "--list":
    cmdList();
    break;
  default:
    console.log(`Usage:
  npx tsx scripts/check-ownership-scoping.ts --scan    Report unscoped id-accepting procedures (exits 1 on violations)
  npx tsx scripts/check-ownership-scoping.ts --list    List every id-accepting procedure and its scope status
`);
    break;
}
