export interface PincodeResult {
  district: string;
  state: string;
}

const PINCODE_MAP: Record<string, PincodeResult> = {
  "110": { district: "New Delhi", state: "Delhi" },
  "120": { district: "Ghaziabad", state: "Uttar Pradesh" },
  "121": { district: "Faridabad", state: "Haryana" },
  "122": { district: "Gurugram", state: "Haryana" },
  "123": { district: "Rewari", state: "Haryana" },
  "124": { district: "Rohtak", state: "Haryana" },
  "125": { district: "Hisar", state: "Haryana" },
  "126": { district: "Jind", state: "Haryana" },
  "127": { district: "Bhiwani", state: "Haryana" },
  "131": { district: "Sonipat", state: "Haryana" },
  "132": { district: "Panipat", state: "Haryana" },
  "133": { district: "Ambala", state: "Haryana" },
  "134": { district: "Panchkula", state: "Haryana" },
  "135": { district: "Yamunanagar", state: "Haryana" },
  "136": { district: "Kaithal", state: "Haryana" },
  "140": { district: "Ludhiana", state: "Punjab" },
  "141": { district: "Ludhiana", state: "Punjab" },
  "142": { district: "Moga", state: "Punjab" },
  "143": { district: "Amritsar", state: "Punjab" },
  "144": { district: "Jalandhar", state: "Punjab" },
  "147": { district: "Patiala", state: "Punjab" },
  "148": { district: "Sangrur", state: "Punjab" },
  "150": { district: "Chandigarh", state: "Chandigarh" },
  "151": { district: "Bathinda", state: "Punjab" },
  "152": { district: "Muktsar", state: "Punjab" },
  "160": { district: "Chandigarh", state: "Chandigarh" },
  "171": { district: "Shimla", state: "Himachal Pradesh" },
  "172": { district: "Kullu", state: "Himachal Pradesh" },
  "173": { district: "Hamirpur", state: "Himachal Pradesh" },
  "176": { district: "Kangra", state: "Himachal Pradesh" },
  "180": { district: "Jammu", state: "Jammu & Kashmir" },
  "190": { district: "Srinagar", state: "Jammu & Kashmir" },
  "201": { district: "Ghaziabad", state: "Uttar Pradesh" },
  "202": { district: "Aligarh", state: "Uttar Pradesh" },
  "203": { district: "Bulandshahr", state: "Uttar Pradesh" },
  "204": { district: "Hathras", state: "Uttar Pradesh" },
  "205": { district: "Etah", state: "Uttar Pradesh" },
  "206": { district: "Etawah", state: "Uttar Pradesh" },
  "207": { district: "Mainpuri", state: "Uttar Pradesh" },
  "208": { district: "Kanpur", state: "Uttar Pradesh" },
  "209": { district: "Fatehpur", state: "Uttar Pradesh" },
  "210": { district: "Banda", state: "Uttar Pradesh" },
  "211": { district: "Prayagraj", state: "Uttar Pradesh" },
  "212": { district: "Pratapgarh", state: "Uttar Pradesh" },
  "221": { district: "Varanasi", state: "Uttar Pradesh" },
  "222": { district: "Jaunpur", state: "Uttar Pradesh" },
  "224": { district: "Ayodhya", state: "Uttar Pradesh" },
  "226": { district: "Lucknow", state: "Uttar Pradesh" },
  "227": { district: "Barabanki", state: "Uttar Pradesh" },
  "228": { district: "Sultanpur", state: "Uttar Pradesh" },
  "229": { district: "Raebareli", state: "Uttar Pradesh" },
  "231": { district: "Mirzapur", state: "Uttar Pradesh" },
  "241": { district: "Shahjahanpur", state: "Uttar Pradesh" },
  "243": { district: "Bareilly", state: "Uttar Pradesh" },
  "244": { district: "Moradabad", state: "Uttar Pradesh" },
  "245": { district: "Meerut", state: "Uttar Pradesh" },
  "246": { district: "Muzaffarnagar", state: "Uttar Pradesh" },
  "247": { district: "Saharanpur", state: "Uttar Pradesh" },
  "248": { district: "Dehradun", state: "Uttarakhand" },
  "249": { district: "Haridwar", state: "Uttarakhand" },
  "250": { district: "Meerut", state: "Uttar Pradesh" },
  "251": { district: "Muzaffarnagar", state: "Uttar Pradesh" },
  "261": { district: "Sitapur", state: "Uttar Pradesh" },
  "263": { district: "Nainital", state: "Uttarakhand" },
  "271": { district: "Gonda", state: "Uttar Pradesh" },
  "273": { district: "Gorakhpur", state: "Uttar Pradesh" },
  "274": { district: "Deoria", state: "Uttar Pradesh" },
  "281": { district: "Mathura", state: "Uttar Pradesh" },
  "282": { district: "Agra", state: "Uttar Pradesh" },
  "283": { district: "Firozabad", state: "Uttar Pradesh" },
  "284": { district: "Jhansi", state: "Uttar Pradesh" },
  "301": { district: "Alwar", state: "Rajasthan" },
  "302": { district: "Jaipur", state: "Rajasthan" },
  "303": { district: "Dausa", state: "Rajasthan" },
  "305": { district: "Ajmer", state: "Rajasthan" },
  "306": { district: "Pali", state: "Rajasthan" },
  "307": { district: "Jodhpur", state: "Rajasthan" },
  "311": { district: "Bhilwara", state: "Rajasthan" },
  "312": { district: "Chittorgarh", state: "Rajasthan" },
  "313": { district: "Udaipur", state: "Rajasthan" },
  "314": { district: "Dungarpur", state: "Rajasthan" },
  "321": { district: "Bharatpur", state: "Rajasthan" },
  "322": { district: "Sawai Madhopur", state: "Rajasthan" },
  "324": { district: "Kota", state: "Rajasthan" },
  "325": { district: "Bundi", state: "Rajasthan" },
  "332": { district: "Sikar", state: "Rajasthan" },
  "333": { district: "Jhunjhunu", state: "Rajasthan" },
  "334": { district: "Bikaner", state: "Rajasthan" },
  "335": { district: "Sri Ganganagar", state: "Rajasthan" },
  "341": { district: "Nagaur", state: "Rajasthan" },
  "342": { district: "Jodhpur", state: "Rajasthan" },
  "343": { district: "Jaisalmer", state: "Rajasthan" },
  "344": { district: "Barmer", state: "Rajasthan" },
  "345": { district: "Jalore", state: "Rajasthan" },
  "360": { district: "Rajkot", state: "Gujarat" },
  "361": { district: "Jamnagar", state: "Gujarat" },
  "362": { district: "Junagadh", state: "Gujarat" },
  "363": { district: "Bhavnagar", state: "Gujarat" },
  "364": { district: "Amreli", state: "Gujarat" },
  "370": { district: "Kutch", state: "Gujarat" },
  "380": { district: "Ahmedabad", state: "Gujarat" },
  "382": { district: "Gandhinagar", state: "Gujarat" },
  "383": { district: "Sabarkantha", state: "Gujarat" },
  "384": { district: "Mehsana", state: "Gujarat" },
  "385": { district: "Banaskantha", state: "Gujarat" },
  "387": { district: "Kheda", state: "Gujarat" },
  "388": { district: "Anand", state: "Gujarat" },
  "389": { district: "Panchmahals", state: "Gujarat" },
  "390": { district: "Vadodara", state: "Gujarat" },
  "392": { district: "Bharuch", state: "Gujarat" },
  "393": { district: "Narmada", state: "Gujarat" },
  "394": { district: "Surat", state: "Gujarat" },
  "395": { district: "Surat", state: "Gujarat" },
  "396": { district: "Navsari", state: "Gujarat" },
  "400": { district: "Mumbai", state: "Maharashtra" },
  "401": { district: "Thane", state: "Maharashtra" },
  "402": { district: "Raigad", state: "Maharashtra" },
  "403": { district: "North Goa", state: "Goa" },
  "410": { district: "Pune", state: "Maharashtra" },
  "411": { district: "Pune", state: "Maharashtra" },
  "412": { district: "Pune", state: "Maharashtra" },
  "413": { district: "Solapur", state: "Maharashtra" },
  "414": { district: "Ahmednagar", state: "Maharashtra" },
  "415": { district: "Satara", state: "Maharashtra" },
  "416": { district: "Kolhapur", state: "Maharashtra" },
  "421": { district: "Thane", state: "Maharashtra" },
  "422": { district: "Nashik", state: "Maharashtra" },
  "423": { district: "Nashik", state: "Maharashtra" },
  "424": { district: "Jalgaon", state: "Maharashtra" },
  "425": { district: "Jalgaon", state: "Maharashtra" },
  "431": { district: "Aurangabad", state: "Maharashtra" },
  "440": { district: "Nagpur", state: "Maharashtra" },
  "441": { district: "Nagpur", state: "Maharashtra" },
  "442": { district: "Wardha", state: "Maharashtra" },
  "444": { district: "Amravati", state: "Maharashtra" },
  "445": { district: "Yavatmal", state: "Maharashtra" },
  "450": { district: "Khandwa", state: "Madhya Pradesh" },
  "451": { district: "Dewas", state: "Madhya Pradesh" },
  "452": { district: "Indore", state: "Madhya Pradesh" },
  "453": { district: "Indore", state: "Madhya Pradesh" },
  "455": { district: "Dhar", state: "Madhya Pradesh" },
  "456": { district: "Ujjain", state: "Madhya Pradesh" },
  "457": { district: "Ratlam", state: "Madhya Pradesh" },
  "458": { district: "Mandsaur", state: "Madhya Pradesh" },
  "460": { district: "Betul", state: "Madhya Pradesh" },
  "461": { district: "Hoshangabad", state: "Madhya Pradesh" },
  "462": { district: "Bhopal", state: "Madhya Pradesh" },
  "470": { district: "Sagar", state: "Madhya Pradesh" },
  "471": { district: "Sagar", state: "Madhya Pradesh" },
  "473": { district: "Guna", state: "Madhya Pradesh" },
  "474": { district: "Gwalior", state: "Madhya Pradesh" },
  "480": { district: "Chhindwara", state: "Madhya Pradesh" },
  "481": { district: "Jabalpur", state: "Madhya Pradesh" },
  "482": { district: "Jabalpur", state: "Madhya Pradesh" },
  "483": { district: "Katni", state: "Madhya Pradesh" },
  "484": { district: "Shahdol", state: "Madhya Pradesh" },
  "486": { district: "Rewa", state: "Madhya Pradesh" },
  "490": { district: "Durg", state: "Chhattisgarh" },
  "491": { district: "Raipur", state: "Chhattisgarh" },
  "492": { district: "Raipur", state: "Chhattisgarh" },
  "493": { district: "Mahasamund", state: "Chhattisgarh" },
  "494": { district: "Bastar", state: "Chhattisgarh" },
  "495": { district: "Bilaspur", state: "Chhattisgarh" },
  "496": { district: "Korba", state: "Chhattisgarh" },
  "497": { district: "Surguja", state: "Chhattisgarh" },
  "500": { district: "Hyderabad", state: "Telangana" },
  "501": { district: "Medak", state: "Telangana" },
  "502": { district: "Rangareddy", state: "Telangana" },
  "503": { district: "Nizamabad", state: "Telangana" },
  "504": { district: "Adilabad", state: "Telangana" },
  "505": { district: "Karimnagar", state: "Telangana" },
  "506": { district: "Warangal", state: "Telangana" },
  "507": { district: "Khammam", state: "Telangana" },
  "508": { district: "Nalgonda", state: "Telangana" },
  "509": { district: "Mahbubnagar", state: "Telangana" },
  "510": { district: "Kurnool", state: "Andhra Pradesh" },
  "515": { district: "Anantapur", state: "Andhra Pradesh" },
  "516": { district: "Kadapa", state: "Andhra Pradesh" },
  "517": { district: "Tirupati", state: "Andhra Pradesh" },
  "518": { district: "Kurnool", state: "Andhra Pradesh" },
  "520": { district: "Krishna", state: "Andhra Pradesh" },
  "521": { district: "Krishna", state: "Andhra Pradesh" },
  "522": { district: "Guntur", state: "Andhra Pradesh" },
  "523": { district: "Prakasam", state: "Andhra Pradesh" },
  "530": { district: "Visakhapatnam", state: "Andhra Pradesh" },
  "531": { district: "Visakhapatnam", state: "Andhra Pradesh" },
  "532": { district: "Srikakulam", state: "Andhra Pradesh" },
  "533": { district: "East Godavari", state: "Andhra Pradesh" },
  "534": { district: "West Godavari", state: "Andhra Pradesh" },
  "560": { district: "Bengaluru", state: "Karnataka" },
  "561": { district: "Bengaluru Rural", state: "Karnataka" },
  "562": { district: "Ramanagara", state: "Karnataka" },
  "563": { district: "Kolar", state: "Karnataka" },
  "570": { district: "Mysuru", state: "Karnataka" },
  "571": { district: "Mandya", state: "Karnataka" },
  "572": { district: "Hassan", state: "Karnataka" },
  "573": { district: "Tumkur", state: "Karnataka" },
  "574": { district: "Dakshina Kannada", state: "Karnataka" },
  "575": { district: "Mangaluru", state: "Karnataka" },
  "576": { district: "Udupi", state: "Karnataka" },
  "577": { district: "Shimoga", state: "Karnataka" },
  "580": { district: "Dharwad", state: "Karnataka" },
  "581": { district: "Haveri", state: "Karnataka" },
  "582": { district: "Raichur", state: "Karnataka" },
  "583": { district: "Bellary", state: "Karnataka" },
  "584": { district: "Gulbarga", state: "Karnataka" },
  "585": { district: "Bidar", state: "Karnataka" },
  "586": { district: "Bagalkot", state: "Karnataka" },
  "587": { district: "Belgaum", state: "Karnataka" },
  "590": { district: "Belgaum", state: "Karnataka" },
  "591": { district: "Belgaum", state: "Karnataka" },
  "600": { district: "Chennai", state: "Tamil Nadu" },
  "601": { district: "Kancheepuram", state: "Tamil Nadu" },
  "602": { district: "Tiruvallur", state: "Tamil Nadu" },
  "603": { district: "Chengalpattu", state: "Tamil Nadu" },
  "604": { district: "Villupuram", state: "Tamil Nadu" },
  "605": { district: "Puducherry", state: "Puducherry" },
  "606": { district: "Cuddalore", state: "Tamil Nadu" },
  "607": { district: "Cuddalore", state: "Tamil Nadu" },
  "608": { district: "Nagapattinam", state: "Tamil Nadu" },
  "609": { district: "Thanjavur", state: "Tamil Nadu" },
  "610": { district: "Thanjavur", state: "Tamil Nadu" },
  "611": { district: "Tiruvarur", state: "Tamil Nadu" },
  "612": { district: "Thanjavur", state: "Tamil Nadu" },
  "613": { district: "Pudukkottai", state: "Tamil Nadu" },
  "614": { district: "Tiruchirapalli", state: "Tamil Nadu" },
  "620": { district: "Tiruchirapalli", state: "Tamil Nadu" },
  "621": { district: "Tiruchirapalli", state: "Tamil Nadu" },
  "622": { district: "Perambalur", state: "Tamil Nadu" },
  "623": { district: "Ramanathapuram", state: "Tamil Nadu" },
  "624": { district: "Dindigul", state: "Tamil Nadu" },
  "625": { district: "Madurai", state: "Tamil Nadu" },
  "626": { district: "Virudhunagar", state: "Tamil Nadu" },
  "627": { district: "Tirunelveli", state: "Tamil Nadu" },
  "628": { district: "Thoothukudi", state: "Tamil Nadu" },
  "629": { district: "Kanyakumari", state: "Tamil Nadu" },
  "630": { district: "Sivagangai", state: "Tamil Nadu" },
  "631": { district: "Kancheepuram", state: "Tamil Nadu" },
  "632": { district: "Vellore", state: "Tamil Nadu" },
  "635": { district: "Krishnagiri", state: "Tamil Nadu" },
  "636": { district: "Salem", state: "Tamil Nadu" },
  "637": { district: "Namakkal", state: "Tamil Nadu" },
  "638": { district: "Erode", state: "Tamil Nadu" },
  "639": { district: "Karur", state: "Tamil Nadu" },
  "640": { district: "Tiruppur", state: "Tamil Nadu" },
  "641": { district: "Coimbatore", state: "Tamil Nadu" },
  "642": { district: "Coimbatore", state: "Tamil Nadu" },
  "643": { district: "Nilgiris", state: "Tamil Nadu" },
  "670": { district: "Kannur", state: "Kerala" },
  "671": { district: "Kasaragod", state: "Kerala" },
  "673": { district: "Kozhikode", state: "Kerala" },
  "674": { district: "Wayanad", state: "Kerala" },
  "676": { district: "Malappuram", state: "Kerala" },
  "678": { district: "Palakkad", state: "Kerala" },
  "679": { district: "Thrissur", state: "Kerala" },
  "680": { district: "Thrissur", state: "Kerala" },
  "682": { district: "Ernakulam", state: "Kerala" },
  "683": { district: "Ernakulam", state: "Kerala" },
  "685": { district: "Idukki", state: "Kerala" },
  "686": { district: "Kottayam", state: "Kerala" },
  "688": { district: "Alappuzha", state: "Kerala" },
  "689": { district: "Pathanamthitta", state: "Kerala" },
  "690": { district: "Kollam", state: "Kerala" },
  "691": { district: "Kollam", state: "Kerala" },
  "695": { district: "Thiruvananthapuram", state: "Kerala" },
  "700": { district: "Kolkata", state: "West Bengal" },
  "711": { district: "Howrah", state: "West Bengal" },
  "712": { district: "Hooghly", state: "West Bengal" },
  "713": { district: "Burdwan", state: "West Bengal" },
  "721": { district: "Midnapore", state: "West Bengal" },
  "731": { district: "Birbhum", state: "West Bengal" },
  "732": { district: "Malda", state: "West Bengal" },
  "734": { district: "Darjeeling", state: "West Bengal" },
  "735": { district: "Jalpaiguri", state: "West Bengal" },
  "736": { district: "Cooch Behar", state: "West Bengal" },
  "737": { district: "Gangtok", state: "Sikkim" },
  "741": { district: "Nadia", state: "West Bengal" },
  "742": { district: "Murshidabad", state: "West Bengal" },
  "743": { district: "North 24 Parganas", state: "West Bengal" },
  "744": { district: "Port Blair", state: "Andaman & Nicobar Islands" },
  "751": { district: "Bhubaneswar", state: "Odisha" },
  "752": { district: "Puri", state: "Odisha" },
  "753": { district: "Cuttack", state: "Odisha" },
  "754": { district: "Dhenkanal", state: "Odisha" },
  "755": { district: "Jajapur", state: "Odisha" },
  "756": { district: "Balasore", state: "Odisha" },
  "757": { district: "Mayurbhanj", state: "Odisha" },
  "758": { district: "Keonjhar", state: "Odisha" },
  "759": { district: "Angul", state: "Odisha" },
  "760": { district: "Berhampur", state: "Odisha" },
  "761": { district: "Rayagada", state: "Odisha" },
  "762": { district: "Koraput", state: "Odisha" },
  "763": { district: "Nabarangpur", state: "Odisha" },
  "764": { district: "Kalahandi", state: "Odisha" },
  "765": { district: "Bolangir", state: "Odisha" },
  "766": { district: "Sambalpur", state: "Odisha" },
  "767": { district: "Bargarh", state: "Odisha" },
  "768": { district: "Jharsuguda", state: "Odisha" },
  "769": { district: "Sundargarh", state: "Odisha" },
  "770": { district: "Rourkela", state: "Odisha" },
  "781": { district: "Kamrup", state: "Assam" },
  "782": { district: "Nagaon", state: "Assam" },
  "783": { district: "Goalpara", state: "Assam" },
  "784": { district: "Sonitpur", state: "Assam" },
  "785": { district: "Jorhat", state: "Assam" },
  "786": { district: "Dibrugarh", state: "Assam" },
  "787": { district: "Tinsukia", state: "Assam" },
  "788": { district: "Cachar", state: "Assam" },
  "790": { district: "Itanagar", state: "Arunachal Pradesh" },
  "793": { district: "Shillong", state: "Meghalaya" },
  "795": { district: "Imphal", state: "Manipur" },
  "796": { district: "Aizawl", state: "Mizoram" },
  "797": { district: "Kohima", state: "Nagaland" },
  "799": { district: "Agartala", state: "Tripura" },
  "800": { district: "Patna", state: "Bihar" },
  "801": { district: "Patna", state: "Bihar" },
  "802": { district: "Bhojpur", state: "Bihar" },
  "803": { district: "Nalanda", state: "Bihar" },
  "804": { district: "Gaya", state: "Bihar" },
  "811": { district: "Munger", state: "Bihar" },
  "812": { district: "Bhagalpur", state: "Bihar" },
  "813": { district: "Banka", state: "Bihar" },
  "814": { district: "Deoghar", state: "Jharkhand" },
  "815": { district: "Giridih", state: "Jharkhand" },
  "816": { district: "Dumka", state: "Jharkhand" },
  "821": { district: "Rohtas", state: "Bihar" },
  "822": { district: "Aurangabad", state: "Bihar" },
  "823": { district: "Nawada", state: "Bihar" },
  "824": { district: "Gaya", state: "Bihar" },
  "825": { district: "Chatra", state: "Jharkhand" },
  "826": { district: "Palamu", state: "Jharkhand" },
  "827": { district: "Bokaro", state: "Jharkhand" },
  "828": { district: "Dhanbad", state: "Jharkhand" },
  "829": { district: "Dhanbad", state: "Jharkhand" },
  "831": { district: "Jamshedpur", state: "Jharkhand" },
  "832": { district: "Seraikela", state: "Jharkhand" },
  "833": { district: "West Singhbhum", state: "Jharkhand" },
  "834": { district: "Ranchi", state: "Jharkhand" },
  "835": { district: "Ranchi", state: "Jharkhand" },
  "841": { district: "Saran", state: "Bihar" },
  "842": { district: "Vaishali", state: "Bihar" },
  "843": { district: "Muzaffarpur", state: "Bihar" },
  "844": { district: "Sitamarhi", state: "Bihar" },
  "845": { district: "East Champaran", state: "Bihar" },
  "846": { district: "Madhubani", state: "Bihar" },
  "847": { district: "Darbhanga", state: "Bihar" },
  "848": { district: "Samastipur", state: "Bihar" },
  "851": { district: "Begusarai", state: "Bihar" },
  "852": { district: "Saharsa", state: "Bihar" },
  "853": { district: "Supaul", state: "Bihar" },
  "854": { district: "Purnia", state: "Bihar" },
  "855": { district: "Katihar", state: "Bihar" },
  "900": { district: "Overseas", state: "Other" },
};

export function lookupPincode(pincode: string): PincodeResult | null {
  if (pincode.length < 3) return null;
  return PINCODE_MAP[pincode.slice(0, 3)] ?? null;
}
